version: "3.9"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: convert
      POSTGRES_PASSWORD: convert
      POSTGRES_DB: convert
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 60s
      timeout: 10s
      retries: 5
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_HOST=db
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy


